"""init

Revision ID: 98d7a7a4ef49
Revises: 6c84ee3f4551
Create Date: 2024-04-26 00:58:25.669443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d7a7a4ef49'
down_revision: Union[str, None] = '6c84ee3f4551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_cart_association', sa.Column('quantity', sa.Integer(), nullable=False), schema='homework')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_cart_association', 'quantity', schema='homework')
    # ### end Alembic commands ###
