"""added_dep_worker

Revision ID: 752e181206d3
Revises: d6dacc7e71a4
Create Date: 2024-04-12 21:10:59.202385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752e181206d3'
down_revision: Union[str, None] = 'd6dacc7e71a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['uuid'], schema='seminar')
    op.create_unique_constraint(None, 'workers', ['uuid'], schema='seminar')

    op.create_table('department_worker',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['seminar.departments.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['seminar.workers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'department_id'),
    schema='seminar'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', schema='seminar', type_='unique')
    op.drop_constraint(None, 'departments', schema='seminar', type_='unique')
    op.drop_table('department_worker', schema='seminar')
    # ### end Alembic commands ###
